apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: rename-pvc
spec:
  version: "{{ .TagName }}"
  homepage: https://github.com/stackitcloud/rename-pvc
  shortDescription: "Rename a PersistentVolumeClaim (PVC)"
  description: |
    rename-pvc renames an existing PersistentVolumeClaim (PVC) by creating a new PVC
    with the same spec and rebinding the existing PersistentClaim (PV) to the newly created PVC.
    Afterwards the old PVC is automatically deleted.
  caveats: "Be sure to create a backup of your data in the PVC before using rename-pvc!"
  platforms:
  - bin: rename-pvc
    {{addURIAndSha "https://github.com/stackitcloud/rename-pvc/releases/download/{{ .TagName }}/rename-pvc-linux-amd64.tar.gz" .TagName }}
    selector:
      matchLabels:
        os: linux
        arch: amd64
  - bin: rename-pvc
    {{addURIAndSha "https://github.com/stackitcloud/rename-pvc/releases/download/{{ .TagName }}/rename-pvc-linux-arm64.tar.gz" .TagName }}
    selector:
      matchLabels:
        os: linux
        arch: arm64
  - bin: rename-pvc
    {{addURIAndSha "https://github.com/stackitcloud/rename-pvc/releases/download/{{ .TagName }}/rename-pvc-darwin-amd64.tar.gz" .TagName }}
    selector:
      matchLabels:
        os: darwin
        arch: amd64
  - bin: rename-pvc
    {{addURIAndSha "https://github.com/stackitcloud/rename-pvc/releases/download/{{ .TagName }}/rename-pvc-darwin-arm64.tar.gz" .TagName }}
    selector:
      matchLabels:
        os: darwin
        arch: arm64
  - bin: rename-pvc.exe
    {{addURIAndSha "https://github.com/stackitcloud/rename-pvc/releases/download/{{ .TagName }}/rename-pvc-windows-amd64.zip" .TagName }}
    selector:
      matchLabels:
        os: windows
        arch: amd64
