---
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: pvc
      mountPath: /test
  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: pvc
